require "test_helper"

# Needs some work - this was generated by lbe with this command
# line: rails generate mini_test:feature CanAccessHome
class CanAccessHomeTest < Capybara::Rails::TestCase
  test "sanity" do
    visit root_path
    assert_content page, "BlogWhiz"
    refute_content page, "Goobye All!"
  end
end
